cxx_binary(
  name = 'basic',
  srcs = [
    'basic.cpp',
  ],
  deps = [
    '//:multi-index',
  ],
)

cxx_binary(
  name = 'bimap',
  srcs = [
    'bimap.cpp',
  ],
  deps = [
    '//:multi-index',
  ],
)
